#------------------------------
# General Site Settings
#
title: Workpattern Library
email: barrie@callenb.org
name: Workpattern Library
description: "Calculates dates and durations whilst taking into account working and non-working times. It creates calendars similar to what you can find in project scheduling software like Microsoft project and Primavera P6."
baseurl: ""
url: "https://workpattern.org"




#------------------------------
# Author Settings
#
author:
  name: "Barrie Callender"
  email: "barrie@callenb.org"
  url: "https://github.com/callenb"
#------------------------------
# Build settings
#
source: .
destination: ./_site
paginate: 10
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "callenb"
year : "2021"

exclude: ['.deploy']
