#------------------------------
# General Site Settings
#
title: Workpattern Library
email: barrie@callenb.org
name: Workpattern Library
description: A library for calculating dates and durations based on working and resting times that can all go down to the nearest minute
baseurl: ""
url: "https://workpattern.org"




#------------------------------
# Author Settings
#
author:
  name: "Barrie Callender"
  email: "barrie@callenb.org"
  url: "https://github.com/callenb"
#------------------------------
twitter:
  username: callenb
  card: summary

social:
  name: Barrie Callender
  links:
    - https://twitter.com/callenb
    - https://www.facebook.com/barrie.callender
    - https://www.linkedin.com/in/barriecallender
    - https://github.com/callenb
    - https://github.com/usingprimavera

# Build settings
#
source: .
destination: ./_site
paginate: 10
paginate_path: /page/:num/
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-last-modified-at

# efault extensions for new posts and pages
post_ext: md
page_ext: html
# Custom variables
owner : "callenb"
year : "2021"

exclude: ['.deploy']
